
package feukora.webservice.rmi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FeuerungsrapportServiceImplService", targetNamespace = "http://rmi.webservice.feukora/", wsdlLocation = "http://localhost:9090/Webserver_Feukora/webservice?wsdl")
public class FeuerungsrapportServiceImplService
    extends Service
{

    private final static URL FEUERUNGSRAPPORTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FEUERUNGSRAPPORTSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName FEUERUNGSRAPPORTSERVICEIMPLSERVICE_QNAME = new QName("http://rmi.webservice.feukora/", "FeuerungsrapportServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/Webserver_Feukora/webservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FEUERUNGSRAPPORTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        FEUERUNGSRAPPORTSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public FeuerungsrapportServiceImplService() {
        super(__getWsdlLocation(), FEUERUNGSRAPPORTSERVICEIMPLSERVICE_QNAME);
    }

    public FeuerungsrapportServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FEUERUNGSRAPPORTSERVICEIMPLSERVICE_QNAME, features);
    }

    public FeuerungsrapportServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, FEUERUNGSRAPPORTSERVICEIMPLSERVICE_QNAME);
    }

    public FeuerungsrapportServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FEUERUNGSRAPPORTSERVICEIMPLSERVICE_QNAME, features);
    }

    public FeuerungsrapportServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FeuerungsrapportServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FeuerungsrapportService
     */
    @WebEndpoint(name = "FeuerungsrapportServiceImplPort")
    public FeuerungsrapportService getFeuerungsrapportServiceImplPort() {
        return super.getPort(new QName("http://rmi.webservice.feukora/", "FeuerungsrapportServiceImplPort"), FeuerungsrapportService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FeuerungsrapportService
     */
    @WebEndpoint(name = "FeuerungsrapportServiceImplPort")
    public FeuerungsrapportService getFeuerungsrapportServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rmi.webservice.feukora/", "FeuerungsrapportServiceImplPort"), FeuerungsrapportService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FEUERUNGSRAPPORTSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw FEUERUNGSRAPPORTSERVICEIMPLSERVICE_EXCEPTION;
        }
        return FEUERUNGSRAPPORTSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
